/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ButtonPrimary: typeof import('./src/components/buttons/ButtonPrimary.vue')['default']
    ButtonSecondary: typeof import('./src/components/buttons/ButtonSecondary.vue')['default']
    ButtonTertiary: typeof import('./src/components/buttons/ButtonTertiary.vue')['default']
    CardAvatar: typeof import('./src/components/CardAvatar.vue')['default']
    CardCheck: typeof import('./src/components/cars/CardCheck.vue')['default']
    CardPackage: typeof import('./src/components/cars/CardPackage.vue')['default']
    CardSupportContact: typeof import('./src/components/cars/CardSupportContact.vue')['default']
    ChipCheck: typeof import('./src/components/chips/ChipCheck.vue')['default']
    ContentHome: typeof import('./src/components/ContentHome.vue')['default']
    Dividir: typeof import('./src/components/Dividir/dividir.vue')['default']
    HeaderHome: typeof import('./src/components/HeaderHome.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconArrowTop: typeof import('./src/components/icons/IconArrowTop.vue')['default']
    IconCheck: typeof import('./src/components/icons/IconCheck.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconPhone: typeof import('./src/components/icons/IconPhone.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    ParallaxComponent: typeof import('./src/components/ParallaxComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
